/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package utils.utilities;

import utils.list.LinkedList;

public class StringUtils {
    public static String join(LinkedList source) {
        return JoinUtils.join(source);
    }

    public static LinkedList split(String source) {
        return SplitUtils.split(source);
    }

    public static boolean isPositiveNumber(String str) { return Integer.parseInt(str) > 0;}
}
